// priority: 5

settings.logAddedRecipes = true
settings.logRemovedRecipes = true
settings.logSkippedRecipes = false
settings.logErroringRecipes = true

console.info('Hello World!  Block recipe script here!  (You will see this line every time server resources reload)')




events.listen('recipes', event => {
  event.remove({id: 'minecraft:lapis_block'})
  event.remove({id: 'minecraft:gold_block'})
  event.remove({id: 'minecraft:iron_block'})
  event.remove({id: 'minecraft:diamond_block'})
  event.remove({id: 'minecraft:emerald_block'})
  event.remove({id: 'minecraft:coal_block'})
  event.remove({id: 'minecraft:netherite_block'})
  event.remove({id: 'minecraft:redstone_block'})
  event.remove({id: 'botania:manasteel_block'})
  event.remove({id: 'botania:terrasteel_block'})
  event.remove({id: 'botania:elementium_block'})
  event.remove({id: 'botania:mana_diamond_block'})
  event.remove({id: 'botania:dragonstone_block'})

  event.remove({id: 'emendatusenigmatica:block_from_ingot/copper'})
  event.remove({id: 'immersiveengineering:crafting/ingot_copper_to_storage_copper'})
  event.remove({id: 'mekanism:processing/copper/storage_blocks/from_ingots'})
  event.remove({id: 'thermal:storage/copper_block'})
  event.remove({id: 'create:crafting/materials/copper_block_from_compacting'})
  event.remove({id: 'tconstruct:common/materials/copper_block_from_ingots'})
  event.remove({id: 'emendatusenigmatica:block_from_ingot/aluminum'})
  event.remove({id: 'immersiveengineering:crafting/ingot_aluminum_to_storage_aluminum'})
  event.remove({id: 'emendatusenigmatica:block_from_ingot/silver'})
  event.remove({id: 'immersiveengineering:crafting/ingot_silver_to_storage_silver'})
  event.remove({id: 'thermal:storage/silver_block'})
  event.remove({id: 'emendatusenigmatica:block_from_ingot/lead'})
  event.remove({id: 'immersiveengineering:crafting/ingot_lead_to_storage_lead'})
  event.remove({id: 'mekanism:processing/lead/storage_blocks/from_ingots'})
  event.remove({id: 'thermal:storage/lead_block'})
  event.remove({id: 'emendatusenigmatica:block_from_ingot/nickel'})
  event.remove({id: 'immersiveengineering:crafting/ingot_nickel_to_storage_nickel'})
  event.remove({id: 'thermal:storage/nickel_block'})
  event.remove({id: 'emendatusenigmatica:block_from_ingot/uranium'})
  event.remove({id: 'immersiveengineering:crafting/ingot_uranium_to_storage_uranium'})
  event.remove({id: 'mekanism:processing/uranium/storage_blocks/from_ingots'})
  event.remove({id: 'biggerreactors:crafting/yellorium_block'})
  event.remove({id: 'emendatusenigmatica:block_from_ingot/osmium'})
  event.remove({id: 'mekanism:processing/osmium/storage_blocks/from_ingots'})
  event.remove({id: 'emendatusenigmatica:block_from_ingot/tin'})
  event.remove({id: 'mekanism:processing/tin/storage_blocks/from_ingots'})
  event.remove({id: 'thermal:storage/tin_block'})
  event.remove({id: 'emendatusenigmatica:block_from_ingot/zinc'})
  event.remove({id: 'create:crafting/materials/zinc_block_from_compacting'})
  event.remove({id: 'emendatusenigmatica:block_from_ingot/bronze'})
  event.remove({id: 'mekanism:storage_blocks/bronze'})
  event.remove({id: 'thermal:storage/bronze_block'})
  event.remove({id: 'emendatusenigmatica:block_from_ingot/brass'})
  event.remove({id: 'create:crafting/materials/brass_block_from_compacting'})
  event.remove({id: 'emendatusenigmatica:block_from_ingot/constantan'})
  event.remove({id: 'immersiveengineering:crafting/ingot_constantan_to_storage_constantan'})
  event.remove({id: 'thermal:storage/constantan_block'})
  event.remove({id: 'emendatusenigmatica:block_from_ingot/electrum'})
  event.remove({id: 'immersiveengineering:crafting/ingot_electrum_to_storage_electrum'})
  event.remove({id: 'thermal:storage/electrum_block'})
  event.remove({id: 'emendatusenigmatica:block_from_ingot/steel'})
  event.remove({id: 'immersiveengineering:crafting/ingot_steel_to_storage_steel'})
  event.remove({id: 'mekanism:storage_blocks/steel'})
  event.remove({id: 'emendatusenigmatica:block_from_ingot/invar'})
  event.remove({id: 'thermal:storage/invar_block'})
  event.remove({id: 'emendatusenigmatica:block_from_ingot/signalum'})
  event.remove({id: 'thermal:storage/signalum_block'})
  event.remove({id: 'emendatusenigmatica:block_from_ingot/lumium'})
  event.remove({id: 'thermal:storage/lumium_block'})
  event.remove({id: 'emendatusenigmatica:block_from_ingot/enderium'})
  event.remove({id: 'thermal:storage/enderium_block'})
  event.remove({id: 'aquaculture:neptunium_block'})
  event.remove({id: 'astralsorcery:shaped/starmetal'})
  event.remove({id: 'mekanism:storage_blocks/refined_obsidian'})
  event.remove({id: 'mekanism:storage_blocks/refined_glowstone'})
  event.remove({id: 'naturesaura:infused_iron_block'})
  event.remove({id: 'naturesaura:tainted_gold_block'})
  event.remove({id: 'pneumaticcraft:compressed_iron_block_from_ingot'})
  event.remove({id: 'biggerreactors:crafting/cyanite_block'})
  event.remove({id: 'biggerreactors:crafting/blutonium_block'})
  event.remove({id: 'biggerreactors:crafting/ludicrite_block'})
  event.remove({id: 'biggerreactors:crafting/graphite_block'})
  event.remove({id: 'minecraft:drenched_iron_block_from_drenched_iron_ingot'})
  event.remove({id: 'minecraft:swift_alloy_block_from_swift_alloy_ingot'})
  event.remove({id: 'minecraft:fireite_block_from_fireite_ingot'})
  event.remove({id: 'extendedcrafting:luminessence_block'})
  event.remove({id: 'extendedcrafting:redstone_ingot_block'})
  event.remove({id: 'extendedcrafting:black_iron_block'})
  event.remove({id: 'extendedcrafting:ender_ingot_block'})
  event.remove({id: 'extendedcrafting:enhanced_ender_ingot_block'})
  event.remove({id: 'extendedcrafting:crystaltine_block'})
  event.remove({id: 'extendedcrafting:the_ultimate_block'})
  event.remove({id: 'extendedcrafting:nether_star_block'})
  event.remove({id: 'extendedcrafting:ender_star_block'})
  event.remove({id: 'mysticalagradditions:insanium_block'})
  event.remove({id: 'mysticalagradditions:insanium_ingot_block'})
  event.remove({id: 'mysticalagradditions:insanium_gemstone_block'})
  event.remove({id: 'mysticalagradditions:insanium_coal_block'})
  event.remove({id: 'mysticalagriculture:prosperity_block'})
  event.remove({id: 'mysticalagriculture:prosperity_ingot_block'})
  event.remove({id: 'mysticalagriculture:prosperity_gemstone_block'})
  event.remove({id: 'mysticalagriculture:inferium_block'})
  event.remove({id: 'mysticalagriculture:inferium_ingot_block'})
  event.remove({id: 'mysticalagriculture:inferium_gemstone_block'})
  event.remove({id: 'mysticalagradditions:inferium_coal_block'})
  event.remove({id: 'mysticalagriculture:prudentium_block'})
  event.remove({id: 'mysticalagriculture:prudentium_ingot_block'})
  event.remove({id: 'mysticalagriculture:prudentium_gemstone_block'})
  event.remove({id: 'mysticalagradditions:prudentium_coal_block'})
  event.remove({id: 'mysticalagriculture:tertium_block'})
  event.remove({id: 'mysticalagriculture:tertium_ingot_block'})
  event.remove({id: 'mysticalagriculture:tertium_gemstone_block'})
  event.remove({id: 'mysticalagradditions:tertium_coal_block'})
  event.remove({id: 'mysticalagriculture:imperium_block'})
  event.remove({id: 'mysticalagriculture:imperium_ingot_block'})
  event.remove({id: 'mysticalagriculture:imperium_gemstone_block'})
  event.remove({id: 'mysticalagradditions:imperium_coal_block'})
  event.remove({id: 'mysticalagriculture:supremium_block'})
  event.remove({id: 'mysticalagriculture:supremium_ingot_block'})
  event.remove({id: 'mysticalagriculture:supremium_gemstone_block'})
  event.remove({id: 'mysticalagradditions:supremium_coal_block'})
  event.remove({id: 'mysticalagriculture:soulium_block'})
  event.remove({id: 'mysticalagriculture:soulium_ingot_block'})
  event.remove({id: 'mysticalagriculture:soulium_gemstone_block'})
  event.remove({id: 'mythicbotany:alfsteel_block_from_ingots'})
  event.remove({id: 'undergarden:cloggrum_block'})
  event.remove({id: 'undergarden:froststeel_block'})
  event.remove({id: 'undergarden:utherium_block'})
  event.remove({id: 'undergarden:regalium_block'})
  event.remove({id: 'undergarden:forgotten_block'})
  event.remove({id: 'powah:crafting/energized_steel_block'})
  event.remove({id: 'powah:crafting/blazing_crystal_block'})
  event.remove({id: 'powah:crafting/niotic_crystal_block'})
  event.remove({id: 'powah:crafting/spirited_crystal_block'})
  event.remove({id: 'powah:crafting/nitro_crystal_block'})
  event.remove({id: 'powah:crafting/uraninite_block'})
  event.remove({id: 'mekanism:storage_blocks/charcoal'})
  event.remove({id: 'quark:building/crafting/compressed/charcoal_block'})
  event.remove({id: 'thermal:storage/charcoal_block'})
  event.remove({id: 'thermal:storage/apatite_block'})
  event.remove({id: 'emendatusenigmatica:block_from_gem/apatite'})
  event.remove({id: 'thermal:storage/cinnabar_block'})
  event.remove({id: 'emendatusenigmatica:block_from_gem/cinnabar'})
  event.remove({id: 'thermal:storage/niter_block'})
  event.remove({id: 'emendatusenigmatica:block_from_gem/potassium_nitrate'}) // niter
  event.remove({id: 'thermal:storage/sulfur_block'})
  event.remove({id: 'emendatusenigmatica:block_from_gem/sulfur'})
  event.remove({id: 'immersiveengineering:crafting/coal_coke_to_coke'})
  event.remove({id: 'thermal:storage/coal_coke_block'})
  event.remove({id: 'emendatusenigmatica:block_from_gem/coke'})
  event.remove({id: 'thermal:storage/bitumen_block'})
  event.remove({id: 'emendatusenigmatica:block_from_gem/bitumen'})
  event.remove({id: 'thermal:storage/tar_block'})
  event.remove({id: 'thermal:storage/rosin_block'})
  event.remove({id: 'thermal:storage/rubber_block'})
  event.remove({id: 'thermal:storage/cured_rubber_block'})
  event.remove({id: 'thermal:storage/slag_block'})
  event.remove({id: 'thermal:storage/rich_slag_block'})
  event.remove({id: 'emendatusenigmatica:block_from_gem/dimensional'})
  event.remove({id: 'emendatusenigmatica:block_from_gem/fluorite'})
  event.remove({id: 'ars_nouveau:mana_gem_block'})
  event.remove({id: 'emendatusenigmatica:block_from_gem/arcane'})
  event.remove({id: 'forbidden_arcanus:arcane_gold_block'})
  event.remove({id: 'forbidden_arcanus:dark_nether_star_block'})
  event.remove({id: 'forbidden_arcanus:stellarite_block'})
  event.remove({id: 'forbidden_arcanus:arcane_crystal_block'})
  event.remove({id: 'emendatusenigmatica:block_from_ingot/cobalt'})
  event.remove({id: 'tconstruct:common/materials/cobalt_block_from_ingots'})
  event.remove({id: 'tconstruct:common/materials/slimesteel_block_from_ingots'})
  event.remove({id: 'tconstruct:common/materials/tinkers_bronze_block_from_ingots'})
  event.remove({id: 'tconstruct:common/materials/rose_gold_block_from_ingots'})
  event.remove({id: 'tconstruct:common/materials/pig_iron_block_from_ingots'})
  event.remove({id: 'tconstruct:common/materials/queens_slime_block_from_ingots'})
  event.remove({id: 'tconstruct:common/materials/manyullyn_block_from_ingots'})
  event.remove({id: 'tconstruct:common/materials/hepatizon_block_from_ingots'})
  event.remove({id: 'tconstruct:tools/modifiers/silky_jewel_block_from_gems'})
//  event.remove({id: })
//  event.remove({id: })
//  event.remove({id: })
//  event.remove({id: })

  const makeBlock = (outputItem, inputTagOrItem) => {
    event.recipes.create.compacting(outputItem, [
		inputTagOrItem, inputTagOrItem, inputTagOrItem,
		inputTagOrItem, inputTagOrItem, inputTagOrItem,
		inputTagOrItem, inputTagOrItem, inputTagOrItem])
  }
  const makeBlockTherm = (outputItem, inputTagOrItem) => {
    event.recipes.create.compacting(outputItem, [
		inputTagOrItem, inputTagOrItem, inputTagOrItem,
		inputTagOrItem, inputTagOrItem, inputTagOrItem,
		inputTagOrItem, inputTagOrItem, inputTagOrItem])
	event.custom({
	  "type": "thermal:press",
	  "input": [
		Ingredient.of(inputTagOrItem, 9),
		{
		  "item": "thermal:press_packing_3x3_die"
		}
	  ],
	  "result": [
		Item.of(outputItem).toResultJson()
	  ],
	  "energy": 400
	})
  }
  const convertBlock = (blockItemTag, convertableTo) => {
	event.stonecutting(convertableTo, blockItemTag)
  }
  makeBlock('appliedenergistics2:sky_stone_small_brick', 'appliedenergistics2:smooth_sky_stone_block')
  makeBlock('appliedenergistics2:sky_stone_brick', 'appliedenergistics2:sky_stone_small_brick')
  makeBlock('minecraft:lapis_block', '#forge:gems/lapis')
  makeBlock('minecraft:gold_block', '#forge:ingots/gold')
  makeBlock('minecraft:iron_block', '#forge:ingots/iron')
  makeBlock('minecraft:diamond_block', '#forge:gems/diamond')
  makeBlock('minecraft:emerald_block', '#forge:gems/emerald')
  makeBlock('minecraft:coal_block', '#minecraft:coals')
  makeBlock('minecraft:netherite_block', '#forge:ingots/netherite')
  makeBlock('minecraft:redstone_block', '#forge:dusts/redstone')
  makeBlockTherm('botania:manasteel_block', '#forge:ingots/manasteel')
  makeBlockTherm('botania:terrasteel_block', '#forge:ingots/terrasteel')
  makeBlockTherm('botania:elementium_block', '#forge:ingots/elementium')
  makeBlockTherm('botania:mana_diamond_block', '#forge:gems/mana_diamond')
  makeBlockTherm('botania:dragonstone_block', '#forge:gems/dragonstone')
  makeBlock('emendatusenigmatica:copper_block', '#forge:ingots/copper')
  convertBlock('#forge:storage_blocks/copper', 'emendatusenigmatica:copper_block')
  convertBlock('#forge:storage_blocks/copper', 'create:copper_block')
  convertBlock('#forge:storage_blocks/copper', 'immersiveengineering:storage_copper')
  convertBlock('#forge:storage_blocks/copper', 'mekanism:block_copper')
  convertBlock('#forge:storage_blocks/copper', 'thermal:copper_block')
  convertBlock('#forge:storage_blocks/copper', 'tconstruct:copper_block')
  makeBlockTherm('emendatusenigmatica:aluminum_block', '#forge:ingots/aluminum')
  convertBlock('#forge:storage_blocks/aluminum', 'emendatusenigmatica:aluminum_block')
  convertBlock('#forge:storage_blocks/aluminum', 'immersiveengineering:storage_aluminum')
  makeBlock('emendatusenigmatica:silver_block', '#forge:ingots/silver')
  convertBlock('#forge:storage_blocks/silver', 'emendatusenigmatica:silver_block')
  convertBlock('#forge:storage_blocks/silver', 'immersiveengineering:storage_silver')
  convertBlock('#forge:storage_blocks/silver', 'thermal:silver_block')
  makeBlock('emendatusenigmatica:lead_block', '#forge:ingots/lead')
  convertBlock('#forge:storage_blocks/lead', 'emendatusenigmatica:lead_block')
  convertBlock('#forge:storage_blocks/lead', 'immersiveengineering:storage_lead')
  convertBlock('#forge:storage_blocks/lead', 'mekanism:block_lead')
  convertBlock('#forge:storage_blocks/lead', 'thermal:lead_block')
  makeBlock('emendatusenigmatica:nickel_block', '#forge:ingots/nickel')
  convertBlock('#forge:storage_blocks/nickel', 'emendatusenigmatica:nickel_block')
  convertBlock('#forge:storage_blocks/nickel', 'immersiveengineering:storage_nickel')
  convertBlock('#forge:storage_blocks/nickel', 'thermal:nickel_block')
  makeBlockTherm('emendatusenigmatica:uranium_block', '#forge:ingots/uranium')
  convertBlock('#forge:storage_blocks/uranium', 'emendatusenigmatica:uranium_block')
  convertBlock('#forge:storage_blocks/uranium', 'immersiveengineering:storage_uranium')
  convertBlock('#forge:storage_blocks/uranium', 'mekanism:block_uranium')
  convertBlock('#forge:storage_blocks/uranium', 'biggerreactors:yellorium_block')
  makeBlockTherm('emendatusenigmatica:osmium_block', '#forge:ingots/osmium')
  convertBlock('#forge:storage_blocks/osmium', 'emendatusenigmatica:osmium_block')
  convertBlock('#forge:storage_blocks/osmium', 'mekanism:block_osmium')
  makeBlock('emendatusenigmatica:tin_block', '#forge:ingots/tin')
  convertBlock('#forge:storage_blocks/tin', 'emendatusenigmatica:tin_block')
  convertBlock('#forge:storage_blocks/tin', 'mekanism:block_tin')
  convertBlock('#forge:storage_blocks/tin', 'thermal:tin_block')
  makeBlockTherm('emendatusenigmatica:zinc_block', '#forge:ingots/zinc')
  convertBlock('#forge:storage_blocks/zinc', 'emendatusenigmatica:zinc_block')
  convertBlock('#forge:storage_blocks/zinc', 'create:zinc_block')
  makeBlock('emendatusenigmatica:bronze_block', '#forge:ingots/bronze')
  convertBlock('#forge:storage_blocks/bronze', 'emendatusenigmatica:bronze_block')
  convertBlock('#forge:storage_blocks/bronze', 'mekanism:block_bronze')
  convertBlock('#forge:storage_blocks/bronze', 'thermal:bronze_block')
  makeBlockTherm('emendatusenigmatica:brass_block', '#forge:ingots/brass')
  convertBlock('#forge:storage_blocks/brass', 'emendatusenigmatica:brass_block')
  convertBlock('#forge:storage_blocks/brass', 'create:brass_block')
  makeBlock('emendatusenigmatica:constantan_block', '#forge:ingots/constantan')
  convertBlock('#forge:storage_blocks/constantan', 'emendatusenigmatica:constantan_block')
  convertBlock('#forge:storage_blocks/constantan', 'immersiveengineering:storage_constantan')
  convertBlock('#forge:storage_blocks/constantan', 'thermal:constantan_block')
  makeBlock('emendatusenigmatica:electrum_block', '#forge:ingots/electrum')
  convertBlock('#forge:storage_blocks/electrum', 'emendatusenigmatica:electrum_block')
  convertBlock('#forge:storage_blocks/electrum', 'immersiveengineering:storage_electrum')
  convertBlock('#forge:storage_blocks/electrum', 'thermal:electrum_block')
  makeBlockTherm('emendatusenigmatica:steel_block', '#forge:ingots/steel')
  convertBlock('#forge:storage_blocks/steel', 'emendatusenigmatica:steel_block')
  convertBlock('#forge:storage_blocks/steel', 'immersiveengineering:storage_steel')
  convertBlock('#forge:storage_blocks/steel', 'mekanism:block_steel')
  makeBlock('emendatusenigmatica:invar_block', '#forge:ingots/invar')
  convertBlock('#forge:storage_blocks/invar', 'emendatusenigmatica:invar_block')
  convertBlock('#forge:storage_blocks/invar', 'thermal:invar_block')
  makeBlock('emendatusenigmatica:signalum_block', '#forge:ingots/signalum')
  convertBlock('#forge:storage_blocks/signalum', 'emendatusenigmatica:signalum_block')
  convertBlock('#forge:storage_blocks/signalum', 'thermal:signalum_block')
  makeBlock('emendatusenigmatica:lumium_block', '#forge:ingots/lumium')
  convertBlock('#forge:storage_blocks/lumium', 'emendatusenigmatica:lumium_block')
  convertBlock('#forge:storage_blocks/lumium', 'thermal:lumium_block')
  makeBlock('emendatusenigmatica:enderium_block', '#forge:ingots/enderium')
  convertBlock('#forge:storage_blocks/enderium', 'emendatusenigmatica:enderium_block')
  convertBlock('#forge:storage_blocks/enderium', 'thermal:enderium_block')
  
  makeBlockTherm('aquaculture:neptunium_block', '#forge:ingots/neptunium')
  makeBlockTherm('astralsorcery:starmetal', '#astralsorcery:starmetal')
  makeBlockTherm('mekanism:block_refined_obsidian', '#forge:ingots/refined_obsidian')
  makeBlockTherm('mekanism:block_refined_glowstone', '#forge:ingots/refined_glowstone')
  makeBlockTherm('naturesaura:infused_iron_block', 'naturesaura:infused_iron')
  makeBlockTherm('naturesaura:tainted_gold_block', 'naturesaura:tainted_gold')
  makeBlockTherm('pneumaticcraft:compressed_iron_block', '#forge:ingots/compressed_iron')
  makeBlockTherm('biggerreactors:cyanite_block', '#forge:ingots/cyanite')
  makeBlockTherm('biggerreactors:blutonium_block', 'biggerreactors:blutonium_ingot')
  makeBlockTherm('biggerreactors:ludicrite_block', '#forge:ingots/ludicrite')
  makeBlockTherm('biggerreactors:graphite_block', '#forge:ingots/graphite')
  makeBlockTherm('elementalcraft:drenched_iron_block', '#forge:ingots/drenched_iron')
  makeBlockTherm('elementalcraft:swift_alloy_block', '#forge:ingots/swift_alloy')
  makeBlockTherm('elementalcraft:fireite_block', '#forge:ingots/fireite')
  makeBlockTherm('extendedcrafting:luminessence_block', 'extendedcrafting:luminessence')
  makeBlockTherm('extendedcrafting:redstone_ingot_block', 'extendedcrafting:redstone_ingot')
  makeBlockTherm('extendedcrafting:black_iron_block', 'extendedcrafting:black_iron_ingot')
  makeBlockTherm('extendedcrafting:ender_ingot_block', 'extendedcrafting:ender_ingot')
  makeBlockTherm('extendedcrafting:enhanced_ender_ingot_block', 'extendedcrafting:enhanced_ender_ingot')
  makeBlockTherm('extendedcrafting:crystaltine_block', 'extendedcrafting:crystaltine_ingot')
  makeBlockTherm('extendedcrafting:the_ultimate_block', 'extendedcrafting:the_ultimate_ingot')
  makeBlockTherm('extendedcrafting:nether_star_block', 'minecraft:nether_star')
  makeBlockTherm('extendedcrafting:ender_star_block', 'extendedcrafting:ender_star')
  makeBlockTherm('mysticalagradditions:insanium_block', 'mysticalagradditions:insanium_essence')
  makeBlockTherm('mysticalagradditions:insanium_ingot_block','mysticalagradditions:insanium_ingot')
  makeBlockTherm('mysticalagradditions:insanium_gemstone_block', 'mysticalagradditions:insanium_gemstone')
  makeBlockTherm('mysticalagradditions:insanium_coal_block', 'mysticalagradditions:insanium_coal')
  makeBlockTherm('mysticalagriculture:prosperity_block','mysticalagriculture:prosperity_shard')
  makeBlockTherm('mysticalagriculture:prosperity_ingot_block','mysticalagriculture:prosperity_ingot')
  makeBlockTherm('mysticalagriculture:prosperity_gemstone_block','mysticalagriculture:prosperity_gemstone')
  makeBlockTherm('mysticalagriculture:inferium_block','mysticalagriculture:inferium_essence')
  makeBlockTherm('mysticalagriculture:inferium_ingot_block','mysticalagriculture:inferium_ingot')
  makeBlockTherm('mysticalagriculture:inferium_gemstone_block','mysticalagriculture:inferium_gemstone')
  makeBlockTherm('mysticalagradditions:inferium_coal_block','mysticalagradditions:inferium_coal')
  makeBlockTherm('mysticalagriculture:prudentium_block','mysticalagriculture:prudentium_essence')
  makeBlockTherm('mysticalagriculture:prudentium_ingot_block','mysticalagriculture:prudentium_ingot')
  makeBlockTherm('mysticalagriculture:prudentium_gemstone_block','mysticalagriculture:prudentium_gemstone')
  makeBlockTherm('mysticalagradditions:prudentium_coal_block','mysticalagradditions:prudentium_coal')
  makeBlockTherm('mysticalagriculture:tertium_block','mysticalagriculture:tertium_essence')
  makeBlockTherm('mysticalagriculture:tertium_ingot_block','mysticalagriculture:tertium_ingot')
  makeBlockTherm('mysticalagriculture:tertium_gemstone_block','mysticalagriculture:tertium_gemstone')
  makeBlockTherm('mysticalagradditions:tertium_coal_block','mysticalagradditions:tertium_coal')
  makeBlockTherm('mysticalagriculture:imperium_block','mysticalagriculture:imperium_essence')
  makeBlockTherm('mysticalagriculture:imperium_ingot_block','mysticalagriculture:imperium_ingot')
  makeBlockTherm('mysticalagriculture:imperium_gemstone_block','mysticalagriculture:imperium_gemstone')
  makeBlockTherm('mysticalagradditions:imperium_coal_block','mysticalagradditions:imperium_coal')
  makeBlockTherm('mysticalagriculture:supremium_block','mysticalagriculture:supremium_essence')
  makeBlockTherm('mysticalagriculture:supremium_ingot_block','mysticalagriculture:supremium_ingot')
  makeBlockTherm('mysticalagriculture:supremium_gemstone_block','mysticalagriculture:supremium_gemstone')
  makeBlockTherm('mysticalagradditions:supremium_coal_block','mysticalagradditions:supremium_coal')
  makeBlockTherm('mysticalagriculture:soulium_block','mysticalagriculture:soulium_dust')
  makeBlockTherm('mysticalagriculture:soulium_ingot_block','mysticalagriculture:soulium_ingot')
  makeBlockTherm('mysticalagriculture:soulium_gemstone_block','mysticalagriculture:soulium_gemstone')
  makeBlockTherm('mythicbotany:alfsteel_block','mythicbotany:alfsteel_ingot')
  makeBlockTherm('undergarden:cloggrum_block','undergarden:cloggrum_ingot')
  makeBlockTherm('undergarden:froststeel_block','undergarden:froststeel_ingot')
  makeBlockTherm('undergarden:utherium_block','undergarden:utherium_ingot')
  makeBlockTherm('undergarden:regalium_block','undergarden:regalium_ingot')
  makeBlockTherm('undergarden:forgotten_block','undergarden:forgotten_ingot')
  makeBlockTherm('powah:energized_steel_block','powah:steel_energized')
  makeBlockTherm('powah:blazing_crystal_block','powah:crystal_blazing')
  makeBlockTherm('powah:niotic_crystal_block','powah:crystal_niotic')
  makeBlockTherm('powah:spirited_crystal_block','powah:crystal_spirited')
  makeBlockTherm('powah:nitro_crystal_block','powah:crystal_nitro')
  makeBlockTherm('powah:uraninite_block','powah:uraninite')
  makeBlock('thermal:charcoal_block', '#forge:charcoal')
  convertBlock('#forge:storage_blocks/charcoal', 'mekanism:block_charcoal')
  convertBlock('#forge:storage_blocks/charcoal', 'quark:charcoal_block')
  convertBlock('#forge:storage_blocks/charcoal', 'thermal:charcoal_block')
  makeBlock('emendatusenigmatica:apatite_block', '#forge:gems/apatite')
  convertBlock('#forge:storage_blocks/apatite', 'emendatusenigmatica:apatite_block')
  convertBlock('#forge:storage_blocks/apatite', 'thermal:apatite_block')
  makeBlock('emendatusenigmatica:cinnabar_block', '#forge:gems/cinnabar')
  convertBlock('#forge:storage_blocks/cinnabar', 'emendatusenigmatica:cinnabar_block')
  convertBlock('#forge:storage_blocks/cinnabar', 'thermal:cinnabar_block')
  makeBlock('emendatusenigmatica:potassium_nitrate_block', '#forge:gems/niter')
  convertBlock('#forge:storage_blocks/niter', 'emendatusenigmatica:potassium_nitrate_block')
  convertBlock('#forge:storage_blocks/niter', 'thermal:niter_block')
  makeBlock('emendatusenigmatica:sulfur_block', '#forge:gems/sulfur')
  convertBlock('#forge:storage_blocks/sulfur', 'emendatusenigmatica:sulfur_block')
  convertBlock('#forge:storage_blocks/sulfur', 'thermal:sulfur_block')
  makeBlock('emendatusenigmatica:coke_block', '#forge:coal_coke')
  convertBlock('#forge:storage_blocks/coal_coke', 'immersiveengineering:coke')
  convertBlock('#forge:storage_blocks/coal_coke', 'thermal:coal_coke_block')
  convertBlock('#forge:storage_blocks/coal_coke', 'emendatusenigmatica:coke_block')
  makeBlock('emendatusenigmatica:bitumen_block', '#forge:bitumen')
  convertBlock('#forge:storage_blocks/bitumen', 'emendatusenigmatica:bitumen_block')
  convertBlock('#forge:storage_blocks/bitumen', 'thermal:bitumen_block')
  makeBlock('thermal:tar_block', '#forge:tar')
  makeBlock('thermal:rosin_block', 'thermal:rosin')
  makeBlock('thermal:rubber_block', 'thermal:rubber')
  makeBlock('thermal:cured_rubber_block', 'thermal:cured_rubber')
  makeBlock('thermal:slag_block', '#forge:slag')
  makeBlock('thermal:rich_slag_block', 'thermal:rich_slag')
  makeBlockTherm('emendatusenigmatica:dimensional_block', '#forge:gems/dimensional')
  makeBlockTherm('emendatusenigmatica:fluorite_block', '#forge:gems/fluorite')
  makeBlockTherm('emendatusenigmatica:arcane_block', '#forge:gems/mana')
  convertBlock('#forge:storage_blocks/mana', 'emendatusenigmatica:arcane_block')
  convertBlock('#forge:storage_blocks/mana', 'ars_nouveau:mana_gem_block')
  makeBlockTherm('forbidden_arcanus:arcane_gold_block', '#forge:ingots/arcane_gold')
  makeBlockTherm('forbidden_arcanus:dark_nether_star_block', 'forbidden_arcanus:dark_nether_star')
  makeBlockTherm('forbidden_arcanus:arcane_crystal_block', '#forge:gems/arcane_crystal')
  makeBlockTherm('forbidden_arcanus:stellarite_block', 'forbidden_arcanus:stellarite_piece')
  makeBlockTherm('emendatusenigmatica:cobalt_block', '#forge:ingots/cobalt')
  convertBlock('#forge:storage_blocks/cobalt', 'emendatusenigmatica:cobalt_block')
  convertBlock('#forge:storage_blocks/cobalt', 'tconstruct:cobalt_block')
  makeBlockTherm('tconstruct:slimesteel_block', '#forge:ingots/slimesteel')
  makeBlockTherm('tconstruct:tinkers_bronze_block', '#forge:ingots/silicon_bronze')
  makeBlockTherm('tconstruct:rose_gold_block', '#forge:ingots/rose_gold')
  makeBlockTherm('tconstruct:pig_iron_block', '#forge:ingots/pig_iron')
  makeBlockTherm('tconstruct:queens_slime_block', '#forge:ingots/queens_slime')
  makeBlockTherm('tconstruct:manyullyn_block', '#forge:ingots/manyullyn')
  makeBlockTherm('tconstruct:hepatizon_block', '#forge:ingots/hepatizon')
  makeBlockTherm('tconstruct:silky_jewel_block', 'tconstruct:silky_jewel')

  convertBlock('#forge:storage_blocks/compressed_cobblestone', 'compressium:cobblestone_1')
  convertBlock('#forge:storage_blocks/compressed_cobblestone', 'excompressum:compressed_cobblestone')
  convertBlock('#forge:storage_blocks/compressed_gravel', 'compressium:gravel_1')
  convertBlock('#forge:storage_blocks/compressed_gravel', 'excompressum:compressed_gravel')
  convertBlock('#forge:storage_blocks/compressed_sand', 'compressium:sand_1')
  convertBlock('#forge:storage_blocks/compressed_sand', 'excompressum:compressed_sand')
  convertBlock('#forge:storage_blocks/compressed_dirt', 'compressium:dirt_1')
  convertBlock('#forge:storage_blocks/compressed_dirt', 'excompressum:compressed_dirt')
  convertBlock('#forge:storage_blocks/compressed_dirt', 'prefab:block_compressed_dirt')
  convertBlock('#forge:storage_blocks/double_compressed_dirt', 'compressium:dirt_2')
  convertBlock('#forge:storage_blocks/double_compressed_dirt', 'prefab:block_double_compressed_dirt')
  convertBlock('#forge:storage_blocks/compressed_netherrack', 'compressium:netherrack_1')
  convertBlock('#forge:storage_blocks/compressed_netherrack', 'excompressum:compressed_netherrack')
  convertBlock('#forge:storage_blocks/compressed_soulsand', 'compressium:soulsand_1')
  convertBlock('#forge:storage_blocks/compressed_soulsand', 'excompressum:compressed_soul_sand')
  convertBlock('#forge:storage_blocks/compressed_endstone', 'compressium:endstone_1')
  convertBlock('#forge:storage_blocks/compressed_endstone', 'excompressum:compressed_end_stone')
  convertBlock('#forge:storage_blocks/compressed_diorite', 'compressium:diorite_1')
  convertBlock('#forge:storage_blocks/compressed_diorite', 'excompressum:compressed_diorite')
  convertBlock('#forge:storage_blocks/compressed_andesite', 'compressium:andesite_1')
  convertBlock('#forge:storage_blocks/compressed_andesite', 'excompressum:compressed_andesite')
  convertBlock('#forge:storage_blocks/compressed_granite', 'compressium:granite_1')
  convertBlock('#forge:storage_blocks/compressed_granite', 'excompressum:compressed_granite')
  convertBlock('#forge:storage_blocks/compressed_stone', 'compressium:stone_1')
  convertBlock('#forge:storage_blocks/compressed_stone', 'prefab:block_compressed_stone')
  convertBlock('#forge:storage_blocks/double_compressed_stone', 'compressium:stone_2')
  convertBlock('#forge:storage_blocks/double_compressed_stone', 'prefab:block_double_compressed_stone')
  convertBlock('#forge:storage_blocks/triple_compressed_stone', 'compressium:stone_3')
  convertBlock('#forge:storage_blocks/triple_compressed_stone', 'prefab:block_triple_compressed_stone')
  convertBlock('#forge:storage_blocks/compressed_obsidian', 'compressium:obsidian_1')
  convertBlock('#forge:storage_blocks/compressed_obsidian', 'prefab:block_compressed_obsidian')
  convertBlock('#forge:storage_blocks/double_compressed_obsidian', 'compressium:obsidian_2')
  convertBlock('#forge:storage_blocks/double_compressed_obsidian', 'prefab:block_double_compressed_obsidian')
  convertBlock('#forge:storage_blocks/fluix', 'emendatusenigmatica:fluix_block')
  convertBlock('#forge:storage_blocks/fluix', 'appliedenergistics2:fluix_block')


// wheat
// eggplant
// carrot
// peanut
// tea
// green bean
// apples
// tomato
// dried kelp
// corn
// nether wart
// golden apples
// sadiroot
// barley
// frost melon
// melon
// cocoa bean
// leather
// beetroot
// coffee cherry
// spinach
// stick
// strawberry
// bell pepper
// hops
// radish
// slime
// sweet berries
// potato
// rice
// packed ice to blue ice
// rabbit hide
// chorus fruit
// onion
// ice to packed ice
// gunpowder
// sugar cane
// bamboo
// sawdust
})