// priority: 10000

settings.logAddedRecipes = true
settings.logRemovedRecipes = true
settings.logSkippedRecipes = false
settings.logErroringRecipes = true

console.info('Hello, World!  Replace Input Script here! (You will see this line every time server resources reload)')

events.listen('recipes', event => {

event.replaceInput({id: 'pedestals:upgrades/itempedestalupgradedefault'}, '#forge:ingots/gold', '#forge:plates/gold')
event.replaceInput({id: 'botania:apothecary_default'}, '#forge:cobblestone', 'create:weathered_limestone_cobblestone')
event.replaceInput({id: 'botania:apothecary_default'}, 'minecraft:cobblestone_slab', 'create:weathered_limestone_cobblestone_slab')
event.replaceInput({id: 'minecraft:piston'}, 'minecraft:redstone', 'extendedcrafting:redstone_ingot')
event.replaceInput({id: 'minecraft:piston'}, 'minecraft:iron_ingot', 'create:piston_extension_pole')
event.replaceInput({id: 'pedestals:pedestal'}, 'minecraft:stone', 'create:polished_limestone')
event.replaceInput({id: 'pedestals:pedestal'}, 'minecraft:stone_slab', 'create:polished_limestone_slab')
event.replaceInput({id: 'pedestals:linkingtool'}, '#forge:rods/wooden', '#forge:rods/treated_wood')
event.replaceInput({id: 'pedestals:linkingtoolbackwards'}, '#forge:rods/wooden', '#forge:rods/treated_wood')
event.replaceInput({id: 'mekanism:transmitter/universal_cable/basic'}, 'minecraft:redstone', 'powah:energy_cable_basic')
event.replaceInput({id: 'simplyjetpacks:ie/thruster_ie1'}, 'immersiveengineering:furnace_heater', 'createaddition:heater')
event.replaceInput({id: 'simplyjetpacks:ie/thruster_ie2'}, 'immersiveengineering:furnace_heater', 'createaddition:heater')
event.replaceInput({id: 'simplyjetpacks:ie/thruster_ie3'}, 'immersiveengineering:furnace_heater', 'createaddition:heater')
event.replaceInput({id: 'rftoolsstorage:storage_module0'}, '#forge:chests', 'immersiveengineering:crate')
event.replaceInput({id: 'minecraft:end_crystal'}, 'minecraft:ender_eye', 'extendedcrafting:ender_star')
event.replaceInput({id: 'minecraft:end_crystal'}, 'minecraft:ghast_tear', 'xreliquary:void_tear')
event.replaceInput({}, 'ceramics:unfired_porcelain','#forge:clay/porcelain')
event.replaceInput({}, 'exnihilosequentia:porcelain_clay','#forge:clay/porcelain')
event.replaceInput({id: 'industrialforegoing:supreme_black_hole_unit'}, '#forge:chests/wooden', 'industrialforegoing:advanced_black_hole_unit')
event.replaceInput({id: 'industrialforegoing:advanced_black_hole_unit'}, '#forge:chests/wooden', 'industrialforegoing:simple_black_hole_unit')
event.replaceInput({id: 'industrialforegoing:simple_black_hole_unit'}, '#forge:chests/wooden', 'industrialforegoing:pity_black_hole_unit')
event.replaceInput({id: 'industrialforegoing:pity_black_hole_unit'}, '#forge:chests/wooden', 'industrialforegoing:common_black_hole_unit')
event.replaceInput({id: 'industrialforegoing:supreme_black_hole_unit'}, 'minecraft:ender_pearl', 'rftoolsbase:infused_enderpearl')
event.replaceInput({id: 'industrialforegoing:advanced_black_hole_unit'}, 'minecraft:ender_pearl', 'rftoolsbase:infused_enderpearl')
event.replaceInput({id: 'industrialforegoing:simple_black_hole_unit'}, 'minecraft:ender_pearl', 'rftoolsbase:infused_enderpearl')
event.replaceInput({id: 'industrialforegoing:pity_black_hole_unit'}, 'minecraft:ender_pearl', 'rftoolsbase:infused_enderpearl')
event.replaceInput({id: 'industrialforegoing:supreme_black_hole_unit'}, 'minecraft:ender_eye', 'powah:ender_core')
event.replaceInput({id: 'industrialforegoing:advanced_black_hole_unit'}, 'minecraft:ender_eye', 'powah:ender_core')
event.replaceInput({id: 'industrialforegoing:simple_black_hole_unit'}, 'minecraft:ender_eye', 'powah:ender_core')
event.replaceInput({id: 'industrialforegoing:pity_black_hole_unit'}, 'minecraft:ender_eye', 'powah:ender_core')
event.replaceInput({id: 'industrialforegoing:common_black_hole_unit'}, '#forge:ingots/iron', '#forge:plastic')
event.replaceInput({id: 'industrialforegoing:supreme_black_hole_tank'}, 'minecraft:bucket', 'industrialforegoing:advanced_black_hole_tank')
event.replaceInput({id: 'industrialforegoing:advanced_black_hole_tank'}, 'minecraft:bucket', 'industrialforegoing:simple_black_hole_tank')
event.replaceInput({id: 'industrialforegoing:simple_black_hole_tank'}, 'minecraft:bucket', 'industrialforegoing:pity_black_hole_tank')
event.replaceInput({id: 'industrialforegoing:pity_black_hole_tank'}, 'minecraft:bucket', 'industrialforegoing:common_black_hole_tank')
event.replaceInput({id: 'industrialforegoing:supreme_black_hole_tank'}, 'minecraft:ender_pearl', 'rftoolsbase:infused_enderpearl')
event.replaceInput({id: 'industrialforegoing:advanced_black_hole_tank'}, 'minecraft:ender_pearl', 'rftoolsbase:infused_enderpearl')
event.replaceInput({id: 'industrialforegoing:simple_black_hole_tank'}, 'minecraft:ender_pearl', 'rftoolsbase:infused_enderpearl')
event.replaceInput({id: 'industrialforegoing:pity_black_hole_tank'}, 'minecraft:ender_pearl', 'rftoolsbase:infused_enderpearl')
event.replaceInput({id: 'industrialforegoing:supreme_black_hole_tank'}, 'minecraft:ender_eye', 'powah:ender_core')
event.replaceInput({id: 'industrialforegoing:advanced_black_hole_tank'}, 'minecraft:ender_eye', 'powah:ender_core')
event.replaceInput({id: 'industrialforegoing:simple_black_hole_tank'}, 'minecraft:ender_eye', 'powah:ender_core')
event.replaceInput({id: 'industrialforegoing:pity_black_hole_tank'}, 'minecraft:ender_eye', 'powah:ender_core')
event.replaceInput({id: 'industrialforegoing:common_black_hole_tank'}, '#forge:ingots/iron', '#forge:plastic')
event.replaceInput({id: 'storagedrawers:iron_storage_upgrade'}, 'storagedrawers:upgrade_template', 'storagedrawers:obsidian_storage_upgrade')
event.replaceInput({id: 'storagedrawers:gold_storage_upgrade'}, 'storagedrawers:upgrade_template', 'storagedrawers:iron_storage_upgrade')
event.replaceInput({id: 'storagedrawers:diamond_storage_upgrade'}, 'storagedrawers:upgrade_template', 'storagedrawers:gold_storage_upgrade')
event.replaceInput({id: 'storagedrawers:emerald_storage_upgrade'}, 'storagedrawers:upgrade_template', 'storagedrawers:diamond_storage_upgrade')
event.replaceInput({}, 'rftoolsbase:dimensionalshard', '#forge:gems/dimensional')
event.replaceInput({}, 'immersiveengineering:slag', '#forge:slag')
event.replaceInput({}, 'thermal:slag', '#forge:slag')
event.replaceInput({id: 'matc:crystals/master_infusion_crystal'}, 'mysticalagriculture:prosperity_shard', 'mysticalagradditions:insanium_gemstone')
event.replaceInput({id: 'matc:crystals/supremium'}, 'mysticalagriculture:prosperity_shard', 'mysticalagriculture:supremium_gemstone')
event.replaceInput({id: 'matc:crystals/imperium'}, 'mysticalagriculture:prosperity_shard', 'mysticalagriculture:imperium_gemstone')
event.replaceInput({id: 'matc:crystals/tertium'}, 'mysticalagriculture:prosperity_shard', 'mysticalagriculture:tertium_gemstone')
event.replaceInput({id: 'matc:crystals/prudentium'}, 'mysticalagriculture:prosperity_shard', 'mysticalagriculture:prudentium_gemstone')
event.replaceInput({id: 'matc:crystals/inferium'}, 'mysticalagriculture:inferium_gemstone', 'appliedenergistics2:purified_certus_quartz_crystal')
event.replaceInput({id: 'matc:crystals/inferium'}, 'mysticalagriculture:prosperity_shard', 'mysticalagriculture:inferium_gemstone')
event.replaceInput({id: 'mysticalagradditions:insanium_gemstone'}, 'mysticalagriculture:prosperity_gemstone', 'mysticalagriculture:supremium_gemstone')
event.replaceInput({id: 'mysticalagriculture:supremium_gemstone'}, 'mysticalagriculture:prosperity_gemstone', 'mysticalagriculture:imperium_gemstone')
event.replaceInput({id: 'mysticalagriculture:imperium_gemstone'}, 'mysticalagriculture:prosperity_gemstone', 'mysticalagriculture:tertium_gemstone')
event.replaceInput({id: 'mysticalagriculture:tertium_gemstone'}, 'mysticalagriculture:prosperity_gemstone', 'mysticalagriculture:prudentium_gemstone')
event.replaceInput({id: 'mysticalagriculture:prudentium_gemstone'}, 'mysticalagriculture:prosperity_gemstone', 'mysticalagriculture:inferium_gemstone')
event.replaceInput({id: 'forbidden_arcanus:silver_dragon_scale'}, '#forge:ingots/iron', '#forge:ingots/silver')
event.replaceInput({id: 'powah:crafting/ender_cell_basic'}, 'minecraft:obsidian', 'powah:energy_cell_basic')
event.replaceInput({id: 'powah:crafting/ender_cell_hardened'}, 'minecraft:obsidian', 'powah:energy_cell_hardened')
event.replaceInput({id: 'powah:crafting/ender_cell_blazing'}, 'minecraft:obsidian', 'powah:energy_cell_blazing')
event.replaceInput({id: 'powah:crafting/ender_cell_niotic'}, 'minecraft:obsidian', 'powah:energy_cell_niotic')
event.replaceInput({id: 'powah:crafting/ender_cell_spirited'}, 'minecraft:obsidian', 'powah:energy_cell_spirited')
event.replaceInput({id: 'powah:crafting/ender_cell_nitro'}, 'minecraft:obsidian', 'powah:energy_cell_nitro')
event.replaceInput({id: 'powah:crafting/reactor_basic'}, 'powah:uraninite', 'powah:reactor_starter')
event.replaceInput({id: 'powah:crafting/reactor_basic'}, 'powah:dielectric_casing', 'powah:uraninite_block')
event.replaceInput({id: 'powah:crafting/reactor_hardened'}, 'powah:uraninite', 'powah:reactor_basic')
event.replaceInput({id: 'powah:crafting/reactor_hardened'}, 'powah:dielectric_casing', 'powah:uraninite_block')
event.replaceInput({id: 'powah:crafting/reactor_blazing'}, 'powah:uraninite', 'powah:reactor_hardened')
event.replaceInput({id: 'powah:crafting/reactor_blazing'}, 'powah:dielectric_casing', 'powah:uraninite_block')
event.replaceInput({id: 'powah:crafting/reactor_niotic'}, 'powah:uraninite', 'powah:reactor_blazing')
event.replaceInput({id: 'powah:crafting/reactor_niotic'}, 'powah:dielectric_casing', 'powah:uraninite_block')
event.replaceInput({id: 'powah:crafting/reactor_spirited'}, 'powah:uraninite', 'powah:reactor_niotic')
event.replaceInput({id: 'powah:crafting/reactor_spirited'}, 'powah:dielectric_casing', 'powah:uraninite_block')
event.replaceInput({id: 'powah:crafting/reactor_nitro'}, 'powah:uraninite', 'powah:reactor_spirited')
event.replaceInput({id: 'powah:crafting/reactor_nitro'}, 'powah:dielectric_casing', 'powah:uraninite_block')
event.replaceInput({id: 'powah:crafting/energy_discharger_basic'}, 'powah:dielectric_casing', 'powah:energy_discharger_starter')
event.replaceInput({id: 'powah:crafting/energy_discharger_hardened'}, 'powah:dielectric_casing', 'powah:energy_discharger_basic')
event.replaceInput({id: 'powah:crafting/energy_discharger_blazing'}, 'powah:dielectric_casing', 'powah:energy_discharger_hardened')
event.replaceInput({id: 'powah:crafting/energy_discharger_niotic'}, 'powah:dielectric_casing', 'powah:energy_discharger_blazing')
event.replaceInput({id: 'powah:crafting/energy_discharger_spirited'}, 'powah:dielectric_casing', 'powah:energy_discharger_niotic')
event.replaceInput({id: 'powah:crafting/energy_discharger_nitro'}, 'powah:dielectric_casing', 'powah:energy_discharger_spirited')
event.replaceInput({id: 'powah:crafting/capacitor_niotic'}, 'powah:capacitor_basic_large', 'powah:capacitor_blazing')
event.replaceInput({id: 'powah:crafting/capacitor_spirited'}, 'powah:capacitor_basic_large', 'powah:capacitor_niotic')
event.replaceInput({id: 'powah:crafting/capacitor_nitro'}, 'powah:capacitor_basic_large', 'powah:capacitor_spirited')
event.replaceInput({mod: 'pipez'}, '#forge:ingots/iron', 'immersiveengineering:fluid_pipe')
event.replaceInput({mod: 'pipez'}, '#forge:dusts/redstone', 'extendedcrafting:redstone_ingot')
event.replaceInput({mod: 'pipez'}, '#forge:storage_blocks/redstone', 'create:precision_mechanism')
event.replaceInput({id: 'portality:frame'}, 'minecraft:stone', 'pneumaticcraft:reinforced_stone')
event.replaceInput({id: 'modularrouters:blank_module'}, '#forge:nuggets/gold', '#forge:wires/electrum')
event.replaceInput({id: 'modularrouters:blank_upgrade'}, '#forge:nuggets/gold', '#forge:wires/electrum')
event.replaceInput({id: 'modularrouters:blank_module'}, '#forge:paper', '#forge:plates/aluminum')
event.replaceInput({id: 'modularrouters:blank_upgrade'}, '#forge:paper', '#forge:plates/aluminum')
event.replaceInput({id: 'modularrouters:item_router'}, '#forge:ingots/iron', '#forge:sheetmetals/iron')
event.replaceInput({mod: 'logisticslasers'}, '#forge:clay', '#forge:silicon')
event.replaceInput({mod: 'logisticslasers'}, '#forge:dusts/redstone', 'extendedcrafting:redstone_ingot')
event.replaceInput({mod: 'logisticslasers'}, '#forge:ingots/iron', '#forge:plates/iron')
event.replaceInput({mod: 'logisticslasers'}, '#forge:nuggets/gold', '#forge:wires/electrum')
event.replaceInput({mod: 'logisticslasers'}, '#forge:glass', 'tconstruct:clear_glass')
event.replaceInput({mod: 'logisticslasers'}, '#forge:glass_panes', 'tconstruct:clear_glass_pane')
event.replaceInput({mod: 'logisticslasers'}, '#forge:gems/diamond', '#forge:plates/diamond')
event.replaceInput({id: 'logisticslasers:controller'}, '#forge:ingots/gold', 'logisticslasers:inventorynode')
event.replaceInput({id: 'fluxnetworks:fluxcore'}, 'minecraft:ender_eye', 'powah:ender_core')
event.replaceInput({mod: 'ironfurnaces'}, '#forge:ingots/iron', '#forge:plates/iron')
event.replaceInput({mod: 'ironfurnaces'}, '#forge:ingots/copper', '#forge:plates/copper')
event.replaceInput({mod: 'ironfurnaces'}, '#forge:ingots/gold', '#forge:plates/gold')
event.replaceInput({mod: 'ironfurnaces'}, '#forge:ingots/silver', '#forge:plates/silver')
event.replaceInput({mod: 'ironfurnaces'}, '#forge:gems/diamond', '#forge:plates/diamond')
event.replaceInput({mod: 'ironfurnaces'}, '#forge:gems/emerald', '#forge:plates/emerald')
event.replaceInput({mod: 'ironfurnaces'}, '#forge:obsidian', '#forge:plates/obsidian')
event.replaceInput({mod: 'ironfurnaces'}, '#forge:glass', 'tconstruct:clear_glass')
event.replaceInput({id: 'mekanismgenerators:generator/heat'}, 'minecraft:furnace', '#forge:furnaces/iron')
event.replaceInput({id: 'mekanism:fuelwood_heater'}, 'minecraft:furnace', '#forge:furnaces/iron')
event.replaceInput({id: 'powah:crafting/furnator_starter'}, 'minecraft:furnace', '#forge:furnaces/iron')
event.replaceInput({id: 'industrialforegoing:material_stonework_factory'}, 'minecraft:furnace', '#forge:furnaces/diamond')
event.replaceInput({id: 'thermal:machine_smelter'}, 'minecraft:blast_furnace', '#forge:furnaces/rainbow')
event.replaceInput({id: 'pneumaticcraft:air_compressor'}, 'minecraft:furnace', '#forge:furnaces/iron')
event.replaceInput({id: 'cyclic:melter'}, 'minecraft:furnace', '#forge:furnaces/iron')
event.replaceInput({id: 'cyclic:solidifier'}, 'minecraft:furnace', '#forge:furnaces/iron')
event.replaceInput({id: 'pickletweaks:watering_can'}, 'minecraft:bowl', 'thermal:watering_can')
event.replaceInput({id: 'pickletweaks:watering_can'}, '#forge:ingots/iron', '#forge:plates/iron')
event.replaceInput({id: 'pickletweaks:reinforced_watering_can'}, 'minecraft:bowl', 'pickletweaks:watering_can')
event.replaceInput({id: 'pickletweaks:reinforced_watering_can'}, '#forge:gems/diamond', '#forge:plates/diamond')
event.replaceInput({type: 'minecraft:crafting_shapeless'}, '#forge:storage_blocks/compressed_cobblestone','#forge:storage_blocks/compressed_cobblestone')
event.replaceInput({type: 'minecraft:crafting_shaped'}, '#forge:storage_blocks/compressed_cobblestone','#forge:storage_blocks/compressed_cobblestone')
event.replaceInput({type: 'minecraft:crafting_shapeless'}, '#forge:storage_blocks/compressed_gravel','#forge:storage_blocks/compressed_gravel')
event.replaceInput({type: 'minecraft:crafting_shaped'}, '#forge:storage_blocks/compressed_gravel','#forge:storage_blocks/compressed_gravel')
event.replaceInput({type: 'minecraft:crafting_shapeless'}, '#forge:storage_blocks/compressed_sand','#forge:storage_blocks/compressed_sand')
event.replaceInput({type: 'minecraft:crafting_shaped'}, '#forge:storage_blocks/compressed_sand','#forge:storage_blocks/compressed_sand')
event.replaceInput({}, '#forge:storage_blocks/compressed_dirt','#forge:storage_blocks/compressed_dirt')
event.replaceInput({}, '#forge:storage_blocks/compressed_netherrack','#forge:storage_blocks/compressed_netherrack')
event.replaceInput({}, '#forge:storage_blocks/compressed_soulsand','#forge:storage_blocks/compressed_soulsand')
event.replaceInput({}, '#forge:storage_blocks/compressed_endstone','#forge:storage_blocks/compressed_endstone')
event.replaceInput({}, '#forge:storage_blocks/compressed_diorite','#forge:storage_blocks/compressed_diorite')
event.replaceInput({}, '#forge:storage_blocks/compressed_andesite','#forge:storage_blocks/compressed_andesite')
event.replaceInput({}, '#forge:storage_blocks/compressed_granite','#forge:storage_blocks/compressed_granite')
event.replaceInput({}, '#forge:storage_blocks/compressed_stone','#forge:storage_blocks/compressed_stone')
event.replaceInput({}, '#forge:storage_blocks/compressed_cobblestone','#forge:storage_blocks/compressed_cobblestone')
event.replaceInput({}, '#forge:storage_blocks/compressed_gravel','#forge:storage_blocks/compressed_gravel')
event.replaceInput({}, '#forge:storage_blocks/compressed_sand','#forge:storage_blocks/compressed_sand')
event.replaceInput({}, '#forge:storage_blocks/compressed_dust','#forge:storage_blocks/compressed_dust')
event.replaceInput({}, '#forge:storage_blocks/double_compressed_stone','#forge:storage_blocks/double_compressed_stone')
event.replaceInput({}, '#forge:storage_blocks/triple_compressed_stone','#forge:storage_blocks/triple_compressed_stone')
event.replaceInput({}, '#forge:storage_blocks/double_compressed_dirt','#forge:storage_blocks/double_compressed_dirt')
event.replaceInput({}, '#forge:storage_blocks/compressed_obsidian','#forge:storage_blocks/compressed_obsidian')
event.replaceInput({}, '#forge:storage_blocks/double_compressed_obsidian','#forge:storage_blocks/double_compressed_obsidian')
event.replaceInput({}, '#forge:storage_blocks/fluix','#forge:storage_blocks/fluix')
event.replaceInput({}, '#forge:bitumen', '#forge:bitumen')
event.replaceInput({}, '#forge:plates/lapis', '#forge:plates/lapis')
event.replaceInput({}, '#forge:plates/lapis_lazuli', '#forge:plates/lapis')
event.replaceInput({id: 'emendatusenigmatica:alloy_dust/enderium'}, '#forge:ender_pearls', '#forge:dusts/ender_pearl')
event.replaceInput({id: 'thermal:enderium_dust_2'}, '#forge:ender_pearls', '#forge:dusts/ender_pearl')
event.replaceInput({id: 'cyclic:mason_steel'}, '#forge:storage_blocks/iron', '#forge:storage_blocks/steel')
event.replaceInput({mod: 'endertanks'}, '#forge:ingots/iron', '#forge:plates/iron')
event.replaceInput({id: 'cobblefordays:tier_2_fluid'}, 'minecraft:glass', 'cobblefordays:tier_1')
event.replaceInput({id: 'cobblefordays:tier_3_fluid'}, 'minecraft:glass', 'cobblefordays:tier_2')
event.replaceInput({id: 'cobblefordays:tier_4_fluid'}, 'minecraft:glass', 'cobblefordays:tier_3')
event.replaceInput({id: 'cobblefordays:tier_5_fluid'}, 'minecraft:glass', 'cobblefordays:tier_4')
event.replaceInput({id: 'prefab:compressed_stone'}, '#forge:stone', 'minecraft:stone')
event.replaceInput({id: 'prefab:ender_gateway'}, '#forge:storage_blocks/quartz', 'minecraft:end_portal_frame')
event.replaceInput({id: 'tesseract:tesseract'}, '#forge:obsidian', 'fluxnetworks:flux_block')
event.replaceInput({id: 'tesseract:tesseract'}, '#forge:ender_pearls', 'botania:ender_air_bottle')
event.replaceInput({id: 'tesseract:tesseract'}, '#forge:storage_blocks/diamond', 'industrialforegoing:machine_frame_advanced')
event.replaceOutput({}, 'ceramics:clay_bucket', 'ceramicbucket:ceramic_bucket')
event.replaceInput({id: 'waterstrainer:strainer_base'}, 'minecraft:hopper', '#excompressum:heavy_sieve')
event.replaceInput({id: 'mekanism:module_gravitational_modulating_unit'}, '#forge:nether_stars', 'angelring:itemring')
event.replaceInput({mod: 'easy_villagers'}, '#forge:glass_panes/colorless', 'tconstruct:clear_glass_pane')
event.replaceInput({mod: 'easy_piglins'}, '#forge:glass_panes/colorless', 'tconstruct:clear_glass_pane')
event.replaceInput({id: 'bagofyurting:bag_of_yurting'}, '#forge:ender_pearls', 'minecraft:ender_eye')
event.replaceInput({}, '#forge:ores/utherium', '#forge:ores/utherium')
event.replaceInput({id: 'bloodmagic:altar/slate'}, '#forge:stone', 'quark:slate')
event.replaceInput({id: 'charginggadgets:charging_station'}, '#forge:storage_blocks/coal', '#forge:furnaces/iron')
event.replaceInput({}, '#forge:dusts/niter', '#forge:dusts/niter')
})