
[world_gen]

	#Customize the world generation of ore
	[world_gen.lava_crystal_stone]
		#enable/disable their world generation
		enable = true
		#Set the vein size
		#Range: 0 ~ 254
		vein_size = 5
		#Set the Y offset, Example: 
		#Offset: 4 - Sets the minimum Y height to 4.
		#Range: 0 ~ 254
		offset = 12
		#Set the vein size, Example: 
		#Range: 8 - Sets the maximum Y height to 8.
		#Range: 0 ~ 254
		range = 20

	#Customize the world generation of ore
	[world_gen.lava_crystal_obsidian]
		#enable/disable their world generation
		enable = true
		#Set the vein size
		#Range: 0 ~ 254
		vein_size = 4
		#Set the Y offset, Example: 
		#Offset: 4 - Sets the minimum Y height to 4.
		#Range: 0 ~ 254
		offset = 6
		#Set the vein size, Example: 
		#Range: 8 - Sets the maximum Y height to 8.
		#Range: 0 ~ 254
		range = 10

	#Customize the world generation of ore
	[world_gen.lava_crystal_compressed]
		#enable/disable their world generation
		enable = true
		#Set the vein size
		#Range: 0 ~ 254
		vein_size = 3
		#Set the Y offset, Example: 
		#Offset: 4 - Sets the minimum Y height to 4.
		#Range: 0 ~ 254
		offset = 0
		#Set the vein size, Example: 
		#Range: 8 - Sets the maximum Y height to 8.
		#Range: 0 ~ 254
		range = 4

	#Customize the world generation of ore
	[world_gen.frost_crystal_stone]
		#enable/disable their world generation
		enable = true
		#Set the vein size
		#Range: 0 ~ 254
		vein_size = 5
		#Set the Y offset, Example: 
		#Offset: 4 - Sets the minimum Y height to 4.
		#Range: 0 ~ 254
		offset = 12
		#Set the vein size, Example: 
		#Range: 8 - Sets the maximum Y height to 8.
		#Range: 0 ~ 254
		range = 20

	#Customize the world generation of ore
	[world_gen.frost_crystal_obsidian]
		#enable/disable their world generation
		enable = true
		#Set the vein size
		#Range: 0 ~ 254
		vein_size = 4
		#Set the Y offset, Example: 
		#Offset: 4 - Sets the minimum Y height to 4.
		#Range: 0 ~ 254
		offset = 6
		#Set the vein size, Example: 
		#Range: 8 - Sets the maximum Y height to 8.
		#Range: 0 ~ 254
		range = 10

	#Customize the world generation of ore
	[world_gen.frost_crystal_compressed]
		#enable/disable their world generation
		enable = true
		#Set the vein size
		#Range: 0 ~ 254
		vein_size = 3
		#Set the Y offset, Example: 
		#Offset: 4 - Sets the minimum Y height to 4.
		#Range: 0 ~ 254
		offset = 0
		#Set the vein size, Example: 
		#Range: 8 - Sets the maximum Y height to 8.
		#Range: 0 ~ 254
		range = 4

