
#Configure advancements
[advancements]
	#Enable/Disable the Thank You 6M advancement
	enableThankYou6M = true

#Configure Items
[items]

	#coal equipment Configuration
	[items.coal]
		#coal armor: enable/disable full set effects
		enableArmorEffects = true
		#coal weapons: enable/disable on hit effects
		enableWeaponEffects = true

	#lapis equipment Configuration
	[items.lapis]
		#lapis armor: enable/disable full set effects
		enableArmorEffects = true
		#lapis weapons: enable/disable on hit effects
		enableWeaponEffects = true

	#redstone equipment Configuration
	[items.redstone]
		#redstone armor: enable/disable full set effects
		enableArmorEffects = true
		#redstone weapons: enable/disable on hit effects
		enableWeaponEffects = true

	#chicken equipment Configuration
	[items.chicken]
		#chicken armor: enable/disable full set effects
		enableArmorEffects = true
		#chicken weapons: enable/disable on hit effects
		enableWeaponEffects = true

	#slime equipment Configuration
	[items.slime]
		#slime armor: enable/disable full set effects
		enableArmorEffects = true
		#slime weapons: enable/disable on hit effects
		enableWeaponEffects = true

	#emerald equipment Configuration
	[items.emerald]
		#emerald armor: enable/disable full set effects
		enableArmorEffects = true
		#emerald weapons: enable/disable on hit effects
		enableWeaponEffects = true

	#obsidian equipment Configuration
	[items.obsidian]
		#obsidian armor: enable/disable full set effects
		enableArmorEffects = true
		#obsidian weapons: enable/disable on hit effects
		enableWeaponEffects = true

	#infused_lava equipment Configuration
	[items.infused_lava]
		#infused_lava armor: enable/disable full set effects
		enableArmorEffects = true
		#infused_lava weapons: enable/disable on hit effects
		enableWeaponEffects = true

		#Infused Lava Extra 
		[items.infused_lava.extra]
			#Infused Lava Tools: Smelting Recipe Input (Blocks)
			smeltingInput = ["minecraft:iron_ore", "minecraft:gold_ore", "minecraft:sand", "minecraft:sandstone", "minecraft:wet_sponge", "minecraft:clay", "minecraft:stone_bricks", "minecraft:cobblestone", "minecraft:stone", "minecraft:acacia_log", "minecraft:birch_log", "minecraft:dark_oak_log", "minecraft:jungle_log", "minecraft:oak_log", "minecraft:spruce_log", "minecraft:netherrack", "minecraft:ancient_debris", "minecraft:stone_bricks"]
			#Infused Lava Tools: Smelting Recipe Output (Items)
			smeltingOutput = ["minecraft:iron_ingot", "minecraft:gold_ingot", "minecraft:glass", "minecraft:smooth_sandstone", "minecraft:sponge", "minecraft:terracotta", "minecraft:cracked_stone_bricks", "minecraft:stone", "minecraft:stone", "minecraft:charcoal", "minecraft:charcoal", "minecraft:charcoal", "minecraft:charcoal", "minecraft:charcoal", "minecraft:charcoal", "minecraft:nether_brick", "minecraft:netherite_scrap", "minecraft:cracked_stone_bricks"]

	#frost equipment Configuration
	[items.frost]
		#frost armor: enable/disable full set effects
		enableArmorEffects = true
		#frost weapons: enable/disable on hit effects
		enableWeaponEffects = true

	#frost_lava equipment Configuration
	[items.frost_lava]
		#frost_lava armor: enable/disable full set effects
		enableArmorEffects = true
		#frost_lava weapons: enable/disable on hit effects
		enableWeaponEffects = true

	#guardian equipment Configuration
	[items.guardian]
		#guardian armor: enable/disable full set effects
		enableArmorEffects = true
		#guardian weapons: enable/disable on hit effects
		enableWeaponEffects = true

	#super_star equipment Configuration
	[items.super_star]
		#super_star armor: enable/disable full set effects
		enableArmorEffects = true
		#super_star weapons: enable/disable on hit effects
		enableWeaponEffects = true

	#ender_dragon equipment Configuration
	[items.ender_dragon]
		#ender_dragon armor: enable/disable full set effects
		enableArmorEffects = true
		#ender_dragon weapons: enable/disable on hit effects
		enableWeaponEffects = true

	#slayer equipment Configuration
	[items.slayer]
		#slayer armor: enable/disable full set effects
		enableArmorEffects = true
		#slayer weapons: enable/disable on hit effects
		enableWeaponEffects = true

