
[theater]
	#
	# Percent chance of generating in an allowed chunk.
	# Default: 50
	#Range: 0 ~ 100
	probability = 50
	#
	# The average distance between structures of this type, measured in chunks.
	# Default: 40
	#Range: > 1
	spacing = 40
	#
	# A random offset applied to spacing. Values closer to 0 produce a grid effect while values closer to spacing are more random.
	# Default: 35
	#Range: > 0
	offset = 35
	#
	# A filter for which biomes this structure should generate in. Works with the biome dictionary using # (#structure_gel:overworld) and "not" statements using ! (!minecraft:plains). These can be combined (!#nether). Operates in the order typed.
	# Example: ["#forge:forest", "!minecraft:flower_forest"] This will add all forests in the biome dictionary and then remove the flower forest.
	# Default: ["dark_forest", "dark_forest_hills"]
	biomes = ["dark_forest", "dark_forest_hills"]
	#
	# How the biomes list should be used. true = whitelist, false = blacklist.
	# Default: true
	is_whitelist = true

