#If set to true, you need to sneak.
sneakingRequired = false
#Should tools being prevented from breaking? If true, mining will be stopped when durability is 1
#If the durability is at 1 when breaking the first block, the tool will still break.
preventBreaking = true
#Should an outline be drawn when holding key to break multiple blocks?
enableOutline = true
#Should the tool's durability be considered when breaking blocks? If having enchantments like Unbreaking, this could show a wrong amount.
considerDurability = false

