#Preferences for outputs from tags used in automatic compat in recipes
tagPreferences = ["minecraft", "emendatusenigmatica", "tconstruct", "tmechworks", "create", "immersiveengineering", "mekanism", "thermalfoundation", "thermalexpansion", "thermal"]

