
["Opolis Utilities Config File"]
	#Cooldown in ticks of the home stone, default = 6000
	"Home Stone Cooldown" = 6000
	#Does the home stone take damge when teleporting, default = true
	"Home Stone Durability" = true
	#URL for your discord
	"Discord URL" = "https://discord.gg/benbenlaw"
	#Modpack name
	"Modpack name" = "TESTMODPACK"
	#Modpack Version
	"Modpack Version" = "VERSION"
	#Mobs basic loot bag drop chance 0.0 = always, 1.0 = never, 0.5 = 50% chance, default = 0.75
	"Mob Drop Chance" = 0.95

