
#Server configuration for Ex Deorum
[server]
	#Whether players in a void world start out with a torch or not.
	starting_torch = true
	#Whether players in a void world start out with a full wooden watering can.
	starting_watering_can = true
	#Whether players can use multiple sieves in a 3x3 area at once.
	simultaneous_sieve_usage = true
	#The progress to increment by each tick for barrel composting and witch water transformation.
	#Range: 0.0 ~ 1.0
	barrel_progress_step = 0.004
	#Whether Witch Water forms netherrack when lava flows into it, allowing for a netherrack version of a cobblestone generator.
	witch_water_netherrack_generator = true
	#Whether the Void World type is used by default in the "server.properties" file when creating a server.
	set_void_world_as_default = false

